version: '3'
services:
    e2e:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: cypress
        environment:
            - CYPRESS_baseUrl=https://example.cypress.io
        volumes:
            - ./cypress.config.ts:/app/cypress.config.ts
            - ./cypress.env.json:/app/cypress.env.json
            - ./cypress:/app/cypress
